### ISSUE TITLE
CSS - Suggestion

### ISSUE THREAD

**Issue by HippyCraig** [playest/better-compendium-list#1]
No issue just a suggestion, I wonder if you try asking the dev team if they can add a class for the next release since I think everthing else does it may have been a simple oversight.  This would streamline your mod.

**Comment by playest** [comment]
I talk [about it here](https://gitlab.com/foundrynet/foundryvtt/-/issues/6552) but no answer so far.

**Comment by HippyCraig** [comment]
cool, the dev team is usually very resposnsive.
