### ISSUE TITLE
Unindentified document class in compendium list: Adventure

### ISSUE THREAD

**Issue by ravingdragoon** [playest/better-compendium-list#2]
I get the following error in my dev console and my adventure module just has the default folder icon.

```
compact-compendium-list.js:34 
 Unindentified document class in compendium list: Adventure
(anonymous)	@	compact-compendium-list.js:34
```
![image](https://user-images.githubusercontent.com/72875320/149996828-15cd9f6d-5050-49e6-a265-984eaceaa813.png)

**Comment by playest** [comment]
That's because I didn't know that Adventure could be a document type ^^ I'm looking into it.
Do you know of any other document type that can appear in this tab?

**Comment by ravingdragoon** [comment]
I'm not aware of any others.

**Comment by playest** [comment]
The last release should fix the problem: https://github.com/playest/compact-compendium-list/releases/tag/v0.0.4

I put a dungeon icon for adventure, if you have a better idea you can look for an icon on [font awesome](https://fontawesome.com/v5.15/icons?d=gallery&p=2), note that the icon must be free, that's the only ones included with FoundryVTT.

**Comment by ravingdragoon** [comment]
Looks good to me! Thanks for the quick update!!!
